name: phylo-prac
channels:
  - bioconda
  - conda-forge
  - eaton-lab
dependencies:
  - python
  - matplotlib
  - numpy
  - biopython
  - mafft
  - Fasttree
  - trimal
  # - ete3
  - toytree
  - toyplot
  - jupyter
